### ISSUE TITLE
memoizedTempFolder functions are unavailable in Android

### ISSUE THREAD

**Issue by davidwadge** [robstoll/tutteli-spek-extensions#15]
Hi there,

I'm attempting to use your library to run tests on a Realm database, however I can't seem to get access to the functions described in the API ("Unresolved reference: newFile").
<img width="503" alt="Screenshot 2019-10-18 at 12 00 35" src="https://user-images.githubusercontent.com/2531750/67089303-2d15ac80-f19f-11e9-9e7b-4057b03afc10.png">

Do I need to do anything other than set the correct testImplementation?
`testImplementation 'ch.tutteli.spek:tutteli-spek-extensions-android:1.0.1'`

If it helps, here's my test stack: 
```
spek_version=2.1.0-alpha.0.3+23b1717
android_junit5_version=1.4.2.0
junit5_runner=0.2.2
jacoco_version=0.8.1
mockk_version=1.9.3`
```

Thanks

**Comment by robstoll** [comment]
wuups, should have tried out the example I made. Write the following:
```
val tempFolder by memoizedTempFolder()
```
instead of 
```
val tempFolder = memoizedTempFolder()
```
and it should work

**Comment by davidwadge** [comment]
Ah I see, works great - thanks.
